# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Stage 1: build
FROM node:lts-alpine AS build
WORKDIR /app

# Install dependencies without running prepare scripts (to avoid double build)
COPY package.json package-lock.json* ./
RUN npm install --ignore-scripts

# Copy source and build
COPY . .
RUN npm run build

# Stage 2: production image
FROM node:lts-alpine
WORKDIR /app

# Copy built files and production dependencies
COPY --from=build /app/build ./build
COPY package.json package-lock.json* ./
RUN npm install --omit=dev --ignore-scripts

# Default environment
ENV NODE_ENV=production

# Entrypoint to start the MCP server
ENTRYPOINT ["node","build/index.js"]
